### ISSUE TITLE
:thinking:

### ISSUE THREAD

**Issue by aliir74** [AUT-CEIT/Apply#1]
:thinking:

**Comment by anewage** [comment]
🐳

**Comment by aliir74** [comment]
@1995parham

**Comment by Tabrizian** [comment]
🤷🏻‍♂️

On Sep 10, 2017, at 5:48 PM, Ali Irani <notifications@github.com<mailto:notifications@github.com>> wrote:


@1995parham<https://github.com/1995parham>

**Comment by anewage** [comment]
How on earth could this repo help? Not trying to be negative, just trying to understand it better.

**Comment by Tabrizian** [comment]
By providing information of those who applied what was their grade how was their CV etc

**Comment by anewage** [comment]
I have a TOEFL exam on Sep. 30th :D that's a little soon :D so I would appreciate if these info provided ASAP :D

**Comment by 1995parham** [comment]
😂 😂 😂

**Comment by aliyazdi75** [comment]
سلام اینا چیه بمنم ایمیل میشه؟🤔😂


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Parham Alvani <notifications@github.com> Date: 9/10/17  10:33 PM  (GMT+03:30) To: AUT-CEIT/Apply <Apply@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [AUT-CEIT/Apply] :thinking: (#1) 
😂 😂 😂

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AUT-CEIT/Apply","title":"AUT-CEIT/Apply","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AUT-CEIT/Apply"}},"updates":{"snippets":[{"icon":"PERSON","message":"@1995parham in #1: 😂 😂 😂 "}],"action":{"name":"View Issue","url":"https://github.com/AUT-CEIT/Apply/issues/1#issuecomment-328360246"}}}-- 
This email was Anti Virus checked by  Security Gateway.
-- 
This email was Anti Virus checked by  Security Gateway.

**Comment by 1995parham** [comment]
یاخدا 😂 هیچی بحث در مورد چگونگی بهره‌بری از آموزه‌های اپلای است

**Comment by aliyazdi75** [comment]
اهان یادم اومد تو گیت فالو کرده بودم😂


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Parham Alvani <notifications@github.com> Date: 9/10/17  11:44 PM  (GMT+03:30) To: AUT-CEIT/Apply <Apply@noreply.github.com> Cc: Ali Yazdi <ma.yazdi75@aut.ac.ir>, Comment <comment@noreply.github.com> Subject: Re: [AUT-CEIT/Apply] :thinking: (#1) 
یاخدا 😂 هیچی بحث در مورد چگونگی بهره‌بری از آموزه‌های اپلای است

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AUT-CEIT/Apply","title":"AUT-CEIT/Apply","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AUT-CEIT/Apply"}},"updates":{"snippets":[{"icon":"PERSON","message":"@1995parham in #1: یاخدا 😂 هیچی بحث در مورد چگونگی بهره‌بری از آموزه‌های اپلای است"}],"action":{"name":"View Issue","url":"https://github.com/AUT-CEIT/Apply/issues/1#issuecomment-328364857"}}}-- 
This email was Anti Virus checked by  Security Gateway.
-- 
This email was Anti Virus checked by  Security Gateway.
